name: batchbuddy
description: BatchBuddy v1 â€“ Student group expense tracker
publish_to: 'none'

version: 1.3.0+1


environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase (REQUIRED for v1)
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F766E"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
